# Pull base image.
FROM dockerfile/ubuntu

# Install Java.
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

#RUN apt-get install openjdk-8-jdk

ADD restful_2017_1491622/ /data/restful_2017_1491622

# Define working directory.
WORKDIR /data/restful_2017_1491622

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

RUN javac WEB-INF/source/com/resful2017/DemoServlet.java -d classes

# Define default command.
CMD ["bash"]